accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'
urlpatterns = [

    path('register/', views.registration, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('musicapp.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

musicapp/models.py
from django.db import models
from django.conf import settings


class Track(models.Model):

    title = models.CharField(max_length=220)
    description = models.TextField(max_length=600)
    track = models.FileField(upload_to='tracks/')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='image/', null=True, blank=True, default='image/default.jpg')

    def __str__(self):

        return self.title
    
class Like(models.Model):

    track = models.ForeignKey(Track, on_delete=models.CASCADE)
    ip_address = models.CharField(max_length=45)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):

        return self.track
    
class Comment(models.Model):

    track_object = models.ForeignKey(Track, related_name='comments', on_delete=models.CASCADE, verbose_name='track')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    created_at = models.DateField(auto_now_add=True)
    text = models.TextField(max_length=400)

    def __str__(self):

        return f"{self.author} in {self.track_object.title}"
    
    
class Playlist(models.Model):

    tracks_list = models.ManyToManyField(Track, related_name='playlists')
    author = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Music Land{% endblock title %}</title>
    {% load static %}
    {% block style %}
    
    <link rel="stylesheet" href="{% static 'base.css' %}">
    {% endblock style %}
</head>
<body>

    <div id="container1">
        <div id="navbar"></div>
        <h1 id="musicland">Music Land</h1>
       {% block links%}
       {% if request.user.is_authenticated %}
       <a href="{% url 'uploadtrack' %}" class="link"><h2 id="upload">Upload</h2></a>
       <a href="{% url 'dashboard' %}" class="link"><h2 id="dashboard">Dashboard</h2></a>
       <a href="{% url 'playlist' %}" class="link"><h2 id="playlist">Playlist</h2></a>
       <a href="{% url 'accounts:logout' %}" class="link"><h2 id="logout">logout</h2></a>
       {% else %}
       <a href="{% url 'accounts:login' %}" class="link"><h2 id="login">Login</h2></a>
       <a href="{% url 'accounts:register' %}" class="link"><h2 id="register">Register</h2></a>
       <a href="{% url 'uploadtrack' %}" class="link"><h2 id="upload">Upload</h2></a>
       <a href="{% url 'dashboard' %}" class="link"><h2 id="dashboard">Dashboard</h2></a>
       <a href="{% url 'playlist' %}" class="link"><h2 id="playlist">Playlist</h2></a>
       {% endif %}
       {% endblock links %}
       
    </div>
    {% block content %}

    {% endblock content %}
    
</body>
</html>

templates/dashboard.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Dashboard{% endblock title %}</title>
    {% block style %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'base.css' %}">
    <link rel="stylesheet" href="{% static 'dashboard.css' %}">
    {% endblock style %}
</head>
<body>
{% block links %}
{% if request.user.is_authenticated %}
 <a href="{% url 'index' %}" class="link"><h2 id="homepage">Home</h2></a>
 <a href="{% url 'playlist' %}" class="link"><h2 id="playlist">Playlist</h2></a>
 <a href="{% url 'uploadtrack' %}" class="link"><h2 id="uploadlink">Upload</h2></a>
 <a href="{% url 'accounts:logout' %}" class="link"><h2 id="logout">logout</h2></a>

{% else %}

 <a href="{% url 'accounts:login' %}" class="link"><h2 id="login">Login</h2></a>
 <a href="{% url 'accounts:register' %}" class="link"><h2 id="register">Register</h2></a>
 <a href="{% url 'index' %}" class="link"><h2 id="homepage">Home</h2></a>
 <a href="{% url 'uploadtrack'}" class="link"><h2 id="uploadlink">Upload</h2></a>
 <a href="{% url 'playlist' %}" class="link"><h2 id="playlist">Playlist</h2></a>
{% endif %}
{% endblock links %}


{% block content %}
<h1 id="mydashboard">Dashboard   :   Songs you uploaded</h1>
{% for item in mytrack %}
<a href="{% url 'track_detail' item.pk %}" class="linkstyle"><h2 id="tracktitle">{{item.title}}</h2></a>
<h1 id="timeofsong">{{item.created_at}}</h1>
{% empty %}

<h1 id="nothing">nothing</h1>

{% endfor %}
{% endblock content %}

</body>
</html>

templates/deleteconfirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Confirm</button>
    </form>
    
    
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Music Land</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'index.css' %}">
</head>
<body>

    <div id="container1">
        <div id="navbar"></div>
        <h1 id="musicland">Music Land</h1>
       {% if request.user.is_authenticated %}
       <a href="{% url 'uploadtrack' %}" class="link"><h2 id="upload">Upload</h2></a>
       <a href="{% url 'dashboard' %}" class="link"><h2 id="dashboard">Dashboard</h2></a>
       <a href="{% url 'playlist' %}" class="link"><h2 id="playlist">Playlist</h2></a>
       <a href="{% url 'accounts:logout' %}" class="link"><h2 id="logout">logout</h2></a>
       {% else %}
       <a href="{% url 'accounts:login' %}" class="link"><h2 id="login">Login</h2></a>
       <a href="{% url 'accounts:register' %}" class="link"><h2 id="register">Register</h2></a>
       <a href="{% url 'uploadtrack' %}" class="link"><h2 id="upload">Upload</h2></a>
       <a href="{% url 'dashboard' %}" class="link"><h2 id="dashboard">Dashboard</h2></a>
       <a href="{% url 'playlist' %}" class="link"><h2 id="playlist">Playlist</h2></a>

       {% endif %}
    </div>
    <div id="container2">
        {% for item in thetrack %}
        <div id="track">
            <a href="{% url 'track_detail' pk=item.pk %}" class="link"><h1 id="title">{{ item.title }}</h1></a>
            <img src="{{ item.image.url }}" id="image">
        </div>
        {% endfor %}
    </div>

    <form method="post" action="{% url 'search_result' %}">
        {% csrf_token %}
        <input placeholder="search..." type="search" name="searched" id="search">
        <button type="submit" id="searchbtn">Search</button>
    </form>
    <img id="headerimg" src="{% static 'headerimg.png' %}">
    <div id="headerimg2"></div>
    <div id="headerimg3"></div>
    <h1 id="headertext1">Python, HTML, CSS</h1>
    <h1 id="created">Created By SoroushGH with Django Framework In Only 1 Week</h1>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <form method="post" enctype="multipart/form-data">{% csrf_token %}

        {{ form.as_p }}
        <button type="submit">Login</button>

    </form>

</body>
</html>

templates/playlist.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Playlist{% endblock title %}</title>
    {% block style %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'base.css' %}">
    <link rel="stylesheet" href="{% static 'playlist.css' %}">
    {% endblock style %}
</head>
<body>
{% block links %}
{% if request.user.is_authenticated %}
<a href="{% url 'index' %}" class="link"><h2 id="homepage">Home</h2></a>
<a href="{% url 'dashboard' %}" class="link"><h2 id="dashboard2">Dashboard</h2></a>
<a href="{% url 'uploadtrack' %}" class="link"><h2 id="uploadlink">Upload</h2></a>
<a href="{% url 'accounts:logout' %}" class="link"><h2 id="logout">logout</h2></a>

{% else %}

<a href="{% url 'accounts:login' %}" class="link"><h2 id="login">Login</h2></a>
<a href="{% url 'accounts:register' %}" class="link"><h2 id="register">Register</h2></a>
<a href="{% url 'index' %}" class="link"><h2 id="homepage">Home</h2></a>
<a href="{% url 'uploadtrack'}" class="link"><h2 id="uploadlink">Upload</h2></a>
<a href="{% url 'dashboard' %}" class="link"><h2 id="dashboard2">Dashboard</h2></a>
{% endif %}
{% endblock links %}
{% block content %}

<h1  id="yourplaylist">The songs in your Playlist </h1>
{% for item in tracks %}
<a href="{% url 'track_detail' pk=item.pk %}" class="link"><h1 id="songs" >{{item.title}}</h1></a>
<h1 id="authortrack">{{item.author}}</h1>
<a href="{% url 'track_detail' pk=item.pk %}" class="link"><img src="{{item.image.url}}" id="songsimage"> </a>
{% empty %}

<h1 id="nosong">You don't have any song in your playlist</h1>

{% endfor %}

{% endblock content %}

</body>
</html>

templates/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <form method="post" enctype="multipart/form-data">
        
        {% csrf_token %}

        {{ form.as_p }}
        <button type="submit">Register</button>

    </form>
</body>
</html>

templates/search_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    {% if searched %}
        <h3>Search result for: {{ searched }}</h3>
    {% endif %}

    {% for result_item in item %}

    <h1>{{ result_item }}</h1>

    {% endfor %}
</body>
</html>

templates/track_detail.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{{track.title}}{% endblock title %}</title>
    {% block style %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'track_detail.css' %}">
    <link rel="stylesheet" href="{% static 'base.css' %}">
    {% endblock style %}
</head>
<body>
    {% block links %}
    {% if request.user.is_authenticated %}
       <a href="{% url 'index' %}" class="link"><h2 id="homepage">Home</h2></a>
       <a href="{% url 'dashboard' %}" class="link"><h2 id="dashboard">Dashboard</h2></a>
       <a href="{% url 'playlist' %}" class="link"><h2 id="playlist">Playlist</h2></a>
       <a href="{% url 'uploadtrack' %}" class="link"><h2 id="uploadlink">Upload</h2></a>
       <a href="{% url 'accounts:logout' %}" class="link"><h2 id="logout">logout</h2></a>

       {% else %}

       <a href="{% url 'accounts:login' %}" class="link"><h2 id="login">Login</h2></a>
       <a href="{% url 'accounts:register' %}" class="link"><h2 id="register">Register</h2></a>
       <a href="{% url 'index' %}" class="link"><h2 id="homepage">Home</h2></a>
       <a href="{% url 'dashboard' %}" class="link"><h2 id="dashboard">Dashboard</h2></a>
       <a href="{% url 'uploadtrack'}" class="link"><h2 id="uploadlink">Upload</h2></a>
       <a href="{% url 'playlist' %}" class="link"><h2 id="playlist">Playlist</h2></a>
       {% endif %}
    {% endblock links %}
    {% block content %}

        <h1 id="tracktitle">{{track.title}}</h1>
      <audio controls id="audio">
        <source src="{{ track.track.url }}" type="audio/mpeg">
      </audio>
      <img src="{{ track.image.url }}" id="trackimg">
      <h3 id="author">Uploader : {{ track.author }}</h3>
      <h3 id="description">{{ track.description }}</h3>
      {% if request.user.is_authenticated and track not in tracks_in_playlist %}
      <form action="{% url 'add_to_playlist' track.pk %}" method="post">{% csrf_token %}
         <button type="submit" id="addtoplaylist">Add To Playlist</button>
      </form>
      {% elif request.user.is_authenticated and track in tracks_in_playlist %}
      <form action="{% url 'remove_from_playlist' track.pk %}" method="post">{% csrf_token %}
         <button type="submit" id="remove_from_playlist">Remove From Playlist</button>
      </form>
      {% else %}


      {% endif %}
      {% if request.user == track.author %}
      <form method="post" action="{% url 'deletetrack' pk=track.pk %}">{% csrf_token %}

         <button type="submit" id="delete">Delete</button>

      </form>
      <a href="{% url 'trackupdate' pk=track.pk %}"><button id="edit">Edit</button></a>
      {% endif %}
    

     <form action="{% url 'liketrack' track.id %}" method="post">{% csrf_token %}

         <button type="submit" id="like"></button>

     </form>


 
    
    <h3 id="createdat">Uploaded in : {{ track.created_at }}</h3>
    <h4 id="likeamount">{{ track.like_set.count }}</h4>
    <h1 id="comments">Comments : {{ comments_count }}</h1>
    {% for comment in comments %}

    <div id="commentobject">
        <h1 id="commentauthor">{{comment.author}}</h1>
        <h3 id="commenttext">{{comment.text}}</h3>
        <h4 id="commenttime">{{comment.created_at}}</h4>
        <hr id="hr">
    </div>

    {% empty %}

    <h2 id="nocomments">No Comments yet.</h2>

    {% endfor %}

    <h1 id="commentlabelform">Add a comment</h1>

    <form method="post">{% csrf_token %}

        {{ form.text }}
        <button type="submit" id="commentbutton">Add</button>

    </form>
{% endblock content %}
</body>
</html>

templates/updatetrack.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit</title>
</head>
<body>

<form method="post" enctype="multipart/form-data">{% csrf_token %}
    <br>
    <br>
    {{ form.title }}
    <br>
    <br>
    {{form.description}}
    <br>
    <br>
    {{form.track}}
    <br>
    <br>
    <button type="submit">Edit</button>
</form>
</body>
</html>

templates/uploadtrack.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}
        Upload Music
        {% endblock title %}
    </title>
    {% block style %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'uploadtrack.css' %}">
    {% endblock style %}
</head>
<body>
    
    
    {% block links %}
    {% if request.user.is_authenticated %}
       <a href="{% url 'index' %}" class="link"><h2 id="homepage">Home</h2></a>
       <a href="{% url 'dashboard' %}" class="link"><h2 id="dashboard">Dashboard</h2></a>
       <a href="{% url 'playlist' %}" class="link"><h2 id="playlist">Playlist</h2></a>
       <a href="{% url 'accounts:logout' %}" class="link"><h2 id="logout">logout</h2></a>
       {% else %}
       <a href="{% url 'accounts:login' %}" class="link"><h2 id="login">Login</h2></a>
       <a href="{% url 'accounts:register' %}" class="link"><h2 id="register">Register</h2></a>
       <a href="{% url 'index' %}" class="link"><h2 id="homepage">Home</h2></a>
       <a href="{% url 'dashboard' %}" class="link"><h2 id="dashboard">Dashboard</h2></a>
       <a href="{% url 'playlist' %}" class="link"><h2 id="playlist">Playlist</h2></a>
       {% endif %}
    {% endblock links %}

    {% block content %}
    <h1 id="uploadtext">Upload a Track</h1>
    <h4 id="labelfortrack">Track :</h4>
    <h4 id="labelforimage">Image :</h4>
    <form method="post" enctype="multipart/form-data">{% csrf_token %}

        {{forms.title}}
        {{forms.description}}
        {{forms.track}}
        {{forms.image}}
        <button type="submit" id="upload">Upload</button>
    </form>
    {% endblock content %}

</body>
</html>